# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KC6GaKxgjuBKMYRz6-ksWZ-U1sVk6D4q

1. Write a Python program to sum all the items in a list.
"""

table = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
n = 0
for i in table:
  n += i
print(n)

"""2. Write a Python program to multiply all the items in a list."""

table = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
n = 1
for i in table:
  n *= i
print(n)

"""3. Write a Python program to get the largest number from a list."""

table = [1, 5, 8, 10, 3252, 35, 67]
for i in table:
  if x < i:
    x = i
print(x)

"""4. Write a Python program to get the smallest number from a list."""

table = [4, 5, 8, 10, 3252, 35, 67]
for i in table:
  if x > i:
    x = i
print(x)

"""5. Write a Python program to remove duplicates from a list."""

table = ["w", "y", "g", "x", "x", "w"]
newtable = []
rep = set()
for i in table:
  if i not in rep:
    newtable.append(i)
    rep.add(i)
print(newtable)

"""6. Write a Python program to check if a list is empty or not."""

table = []
if len(table) == 0:
  print("empty")
else:
  print("not empty")

"""7. Write a Python program to clone or copy a list."""

table = ["w", "y", "g", "x", "x", "w"]
newtable = table.copy()
print(newtable)

"""8. Write a Python program to access the index of a list.

"""

table = ["w", "y", "g", "x", "x", "w"]
for index, x in enumerate(table):
  print("item:", x, "and its index:", index)

"""9. Write a Python program to convert a list of characters into a string."""

table = ["w", "y", "g", "x", "x", "w"]
string = ""
for x in table:
  string += x
print(string)

"""10. Write a Python program to find the index of an item in a specified list."""

table = ["w", "y", "g", "x2", "x", "w3"]
item = input()
for index, x in enumerate(table):
  if x == item:
    print(index)

11. Write a Python program to append a list to the second list.

table = ["a", "b", "c"]
secondtable = [1, 2, 3]
secondtable.extend(table)
print(secondtable)

"""12. Write a Python program to select an item randomly from a list."""

import random
table = ["w", "y", "g", "x2", "x", "w3"]
print(table[random.randint(0, 5)])

"""13. Write a Python program to find the second smallest number in a list."""

table = [1, 6, 8, 14, 346, 23, -1]
table.sort()
print(table[1])

"""14. Write a Python program to find the second largest number in a list."""

table = [1, 6, 8, 14, 346, 23, -1]
table.sort(reverse=True)
print(table[1])

"""15. Write a Python program to get unique values from a list.


"""

table = ["abc", "acb", "abc", 1, 3, 1, 5, 3, 56, 5]
uniquetable = set(table)
secondtable = list(uniquetable)
print(secondtable)

"""16. Write a Python program to get the frequency of elements in a list."""

table = ["abc", "acb", "abc", 1, 3, 1, 5, 3, 56, 5]
freq = {}
for x in table:
    keys = freq.keys()
    if x in keys:
        freq[x] += 1
    else:
        freq[x] = 1
print(freq)

"""17. Write a Python program to count the number of elements in a list within a specified range."""

table = [10, 15, 13, 100, 650, 434, 3771, 1000]
count = 0
for num in table:
  if 20 <= num <= 1000:
    count += 1
print(num)

"""18. Write a Python program to check whether a list contains a sublist."""

table = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
firstsub = [1, 2, 3]
secondsub = [4, 5, 2]
def checksublist(main, sub):
  tablen = len(sub)
  for i in range(len(main) - tablen + 1):
    if main[i:i + tablen] == sub:
      return True
  return False
print(checksublist(table, firstsub))

"""19. Write a Python program to convert a list of multiple integers into a single integer."""

table = [1, 6, 5, 2, 3, 5]
stringtable = []
final = 0
for x in table:
  stringtable.append(str(x))
joinedtable = ''.join(stringtable)
final = int(joinedtable)
print(final)

"""20. Write a Python program to select the odd items from a list."""

table = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
oddtable = []
for x in table:
  if x % 2 != 0:
    oddtable.append(x)
print(oddtable)